apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: de1kacq3c-python 
  janus-idp.io/tekton: de1kacq3c-python
  backstage.io/kubernetes-id: de1kacq3c-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: de1kacq3c-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  